/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_OUE_WRAP_H_
#define SWIG_OUE_WRAP_H_

namespace Swig {
  class Director;
}


class SwigDirector_Scene : public Scene, public Swig::Director {

public:
    SwigDirector_Scene(VALUE self);
    virtual void update(float dt);
    virtual ~SwigDirector_Scene();
};


class SwigDirector_InputReceiver : public OneU::IInputReceiver, public Swig::Director {

public:
    SwigDirector_InputReceiver(VALUE self);
    virtual ~SwigDirector_InputReceiver();
    virtual bool onChar(OneU::CharEvent const &event);
    virtual bool onKey(OneU::KeyEvent const &event);
    virtual bool onMouse(OneU::MouseEvent const &event);
};


#endif
